# Generated by Django 4.1.1 on 2022-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
